name: Node.JS CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn test
        env:
          CI: true
          RUN_SLOW_TESTS: true
